apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        300
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Refresh_Interval  5

    [OUTPUT]
        Name              s3
        Match             kube.*
        bucket            your-s3-bucket-name
        region            your-aws-region
        total_file_size   5M
        upload_timeout    10m
        store_dir         /tmp/fluent-bit/s3
        s3_key_format     /logs/$TAG/%Y/%m/%d/%H/%M/%S.gz
        compression       gzip

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
