global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.31.94.92:9100']

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['172.31.94.92:8080']
